site_name: PyTensordock Documentation
site_author: Nishant Gajjar

edit_uri: edit/main/docs/

# Repository
repo_name: nishantg96/pytensordock
repo_url: https://github.com/nishantg96/pytensordock

# Copyright
copyright: Copyright &copy; 2023 - 2024 Nishant Gajjar


theme:
  name: readthedocs
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Roboto
    code: Roboto Mono
  collapse_navigation: false
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Extensions
markdown_extensions:
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkapi:
      src_dirs: [src]
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
nav:
    - Home: index.md
            
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/nishantg96/pytensordock'